packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  electron: true
  esbuild: true
  koffi: true
  msgpackr-extract: true
  msw: true
  protobufjs: true

catalog:
  "@orpc/contract": "^1.13.13"
  "effect": "4.0.0-beta.36"

pnpm:
  onlyBuiltDependencies:
    - esbuild
    - lightningcss
    - msgpackr-extract
    - msw
  overrides:
    vite: "npm:@voidzero-dev/vite-plus-core@latest"
    vitest: "npm:@voidzero-dev/vite-plus-test@latest"
