/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppProjectIdRouteImport } from './routes/app/$projectId'
import { Route as AppProjectIdIndexRouteImport } from './routes/app/$projectId/index'
import { Route as AppProjectIdDashboardIndexRouteImport } from './routes/app/$projectId/dashboard.index'
import { Route as AppProjectIdAgentIndexRouteImport } from './routes/app/$projectId/agent.index'
import { Route as AppProjectIdAgentSessionIdRouteImport } from './routes/app/$projectId/agent.$sessionId'
import { Route as AppProjectIdTerminalTerminalIdIndexRouteImport } from './routes/app/$projectId/terminal/$terminalId.index'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectIdRoute = AppProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectIdIndexRoute = AppProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProjectIdRoute,
} as any)
const AppProjectIdDashboardIndexRoute =
  AppProjectIdDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AppProjectIdRoute,
  } as any)
const AppProjectIdAgentIndexRoute = AppProjectIdAgentIndexRouteImport.update({
  id: '/agent/',
  path: '/agent/',
  getParentRoute: () => AppProjectIdRoute,
} as any)
const AppProjectIdAgentSessionIdRoute =
  AppProjectIdAgentSessionIdRouteImport.update({
    id: '/agent/$sessionId',
    path: '/agent/$sessionId',
    getParentRoute: () => AppProjectIdRoute,
  } as any)
const AppProjectIdTerminalTerminalIdIndexRoute =
  AppProjectIdTerminalTerminalIdIndexRouteImport.update({
    id: '/terminal/$terminalId/',
    path: '/terminal/$terminalId/',
    getParentRoute: () => AppProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/$projectId': typeof AppProjectIdRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/$projectId/': typeof AppProjectIdIndexRoute
  '/app/$projectId/agent/$sessionId': typeof AppProjectIdAgentSessionIdRoute
  '/app/$projectId/agent/': typeof AppProjectIdAgentIndexRoute
  '/app/$projectId/dashboard/': typeof AppProjectIdDashboardIndexRoute
  '/app/$projectId/terminal/$terminalId/': typeof AppProjectIdTerminalTerminalIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppIndexRoute
  '/app/$projectId': typeof AppProjectIdIndexRoute
  '/app/$projectId/agent/$sessionId': typeof AppProjectIdAgentSessionIdRoute
  '/app/$projectId/agent': typeof AppProjectIdAgentIndexRoute
  '/app/$projectId/dashboard': typeof AppProjectIdDashboardIndexRoute
  '/app/$projectId/terminal/$terminalId': typeof AppProjectIdTerminalTerminalIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/$projectId': typeof AppProjectIdRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/$projectId/': typeof AppProjectIdIndexRoute
  '/app/$projectId/agent/$sessionId': typeof AppProjectIdAgentSessionIdRoute
  '/app/$projectId/agent/': typeof AppProjectIdAgentIndexRoute
  '/app/$projectId/dashboard/': typeof AppProjectIdDashboardIndexRoute
  '/app/$projectId/terminal/$terminalId/': typeof AppProjectIdTerminalTerminalIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/$projectId'
    | '/app/'
    | '/app/$projectId/'
    | '/app/$projectId/agent/$sessionId'
    | '/app/$projectId/agent/'
    | '/app/$projectId/dashboard/'
    | '/app/$projectId/terminal/$terminalId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/$projectId'
    | '/app/$projectId/agent/$sessionId'
    | '/app/$projectId/agent'
    | '/app/$projectId/dashboard'
    | '/app/$projectId/terminal/$terminalId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/$projectId'
    | '/app/'
    | '/app/$projectId/'
    | '/app/$projectId/agent/$sessionId'
    | '/app/$projectId/agent/'
    | '/app/$projectId/dashboard/'
    | '/app/$projectId/terminal/$terminalId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$projectId': {
      id: '/app/$projectId'
      path: '/$projectId'
      fullPath: '/app/$projectId'
      preLoaderRoute: typeof AppProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$projectId/': {
      id: '/app/$projectId/'
      path: '/'
      fullPath: '/app/$projectId/'
      preLoaderRoute: typeof AppProjectIdIndexRouteImport
      parentRoute: typeof AppProjectIdRoute
    }
    '/app/$projectId/dashboard/': {
      id: '/app/$projectId/dashboard/'
      path: '/dashboard'
      fullPath: '/app/$projectId/dashboard/'
      preLoaderRoute: typeof AppProjectIdDashboardIndexRouteImport
      parentRoute: typeof AppProjectIdRoute
    }
    '/app/$projectId/agent/': {
      id: '/app/$projectId/agent/'
      path: '/agent'
      fullPath: '/app/$projectId/agent/'
      preLoaderRoute: typeof AppProjectIdAgentIndexRouteImport
      parentRoute: typeof AppProjectIdRoute
    }
    '/app/$projectId/agent/$sessionId': {
      id: '/app/$projectId/agent/$sessionId'
      path: '/agent/$sessionId'
      fullPath: '/app/$projectId/agent/$sessionId'
      preLoaderRoute: typeof AppProjectIdAgentSessionIdRouteImport
      parentRoute: typeof AppProjectIdRoute
    }
    '/app/$projectId/terminal/$terminalId/': {
      id: '/app/$projectId/terminal/$terminalId/'
      path: '/terminal/$terminalId'
      fullPath: '/app/$projectId/terminal/$terminalId/'
      preLoaderRoute: typeof AppProjectIdTerminalTerminalIdIndexRouteImport
      parentRoute: typeof AppProjectIdRoute
    }
  }
}

interface AppProjectIdRouteChildren {
  AppProjectIdIndexRoute: typeof AppProjectIdIndexRoute
  AppProjectIdAgentSessionIdRoute: typeof AppProjectIdAgentSessionIdRoute
  AppProjectIdAgentIndexRoute: typeof AppProjectIdAgentIndexRoute
  AppProjectIdDashboardIndexRoute: typeof AppProjectIdDashboardIndexRoute
  AppProjectIdTerminalTerminalIdIndexRoute: typeof AppProjectIdTerminalTerminalIdIndexRoute
}

const AppProjectIdRouteChildren: AppProjectIdRouteChildren = {
  AppProjectIdIndexRoute: AppProjectIdIndexRoute,
  AppProjectIdAgentSessionIdRoute: AppProjectIdAgentSessionIdRoute,
  AppProjectIdAgentIndexRoute: AppProjectIdAgentIndexRoute,
  AppProjectIdDashboardIndexRoute: AppProjectIdDashboardIndexRoute,
  AppProjectIdTerminalTerminalIdIndexRoute:
    AppProjectIdTerminalTerminalIdIndexRoute,
}

const AppProjectIdRouteWithChildren = AppProjectIdRoute._addFileChildren(
  AppProjectIdRouteChildren,
)

interface AppRouteChildren {
  AppProjectIdRoute: typeof AppProjectIdRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProjectIdRoute: AppProjectIdRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
